name: responsive_news_platform
description: Responsive Flutter news platform - GoRouter, Material 3, adaptive layouts, Hero, persisted theme.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
